version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Install Prequisites"
      - echo $DOCKER_IMAGE_NAME
      - echo $DOCKER_IMAGE_TAG
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_REGION
      # - apt-get update
      # - apt-get install -y curl
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Building the Docker image...
      - cd $CODEBUILD_SRC_DIR
      - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
      - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - echo Build completed
      - docker images
      - docker run -p 49160:8000 -d $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - docker ps
      # - curl -i 0.0.0.0:49160
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG